# Site settings
title: In praise of randomness
email: axelexic@gmail.com
description: Decrypting modern cryptography
baseurl: ""
url: "http://axelexic.github.io"
twitter_username: axelexic
github_username:  axelexic
encoding: utf-8

# Giscus comments
giscus:
  enabled: true
  repo: "axelexic/axelexic.github.io"
  repo_id: "MDEwOlJlcG9zaXRvcnkyODA3MDAyNzI="
  category: "Announcements"
  category_id: "DIC_kwDOELslcM4C9uY1"
  mapping: "pathname"
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: "noborder_light"
  lang: "en"
  loading: "lazy"

# Build settings
markdown: kramdown
kramdown:
  input: Kramdown
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-last-modified-at

last-modified-at:
    date-format: '%d-%b-%Y'
